### ISSUE TITLE
Restore the Organizations dropdown

### ISSUE THREAD

**Issue by ludovic-gonthier** [ludovic-gonthier/snowshoe#17]
Restore the organizations dropdown to be able to choose which organizations teams we want to see.

**Comment by fpietka** [comment]
:+1: Right now it gets all organization but doesn't compute all teams either.

**Comment by fpietka** [comment]
When you say restore, is it something you already have code for? I can't see any branch.
For now, I hacked it so I could filter only one organization.

**Comment by ludovic-gonthier** [comment]
I'm currently working on it.
I saying restore because because it was here in a previous version.

The commit a64f7b95e9ec8ea5872de99606825c8cb25f850c removed the button.
A revert of this commit won't just re-enable the button since the view logic has changed in-between.
