### ISSUE TITLE
Do not consume all API rate

### ISSUE THREAD

**Issue by ludovic-gonthier** [ludovic-gonthier/snowshoe#18]
## Description

When there is a consequent number of PR, all the Github API rate-limit is consumed, therefore the user is no longer available to use composer or other application that requires github calls.
## Actions

Stop the Github API call when the rate limit reach a defined number.
This number should be configurable.

**Comment by fpietka** [comment]
Something that might help on that:
https://developer.github.com/v3/#conditional-requests

**Comment by ludovic-gonthier** [comment]
Indeed, that could help to greatly reduce API calls, thanks!

**Comment by ludovic-gonthier** [comment]
API Consumption reduced to only a few hundreds per hour.

With the ETag, the poll timeout can be decreased significantly without impacting the API Rate consumption. (We're now running on a polling time of 15 seconds)

**Comment by fpietka** [comment]
Where is that option located? is it related to GITHUB_POLL_TIMEOUT ?

**Comment by ludovic-gonthier** [comment]
Yes, this is the option to modify the polling time (in seconds. 60 seconds, by default).

**Comment by fpietka** [comment]
Ok. Maybe it needs to be renamed, because `timeout` is misleading.
By the way it is working great!

**Comment by ludovic-gonthier** [comment]
Ok, I'll search for a better naming then. Glad to here it's working :)
