### ISSUE TITLE
Screenshot in readme to preview the tool

### ISSUE THREAD

**Issue by fpietka** [ludovic-gonthier/snowshoe#19]
Would be nice to have a screenshot of the result in the readme. Nothing fancy, but like in the GTR readme :grin:

**Comment by ludovic-gonthier** [comment]
Sorry for the late response, the notifications went into the flood of other repositories.
Won't happen again.

I will update this today

**Comment by ludovic-gonthier** [comment]
Closed at 8b9fb068024e46d153081d52926bf857b73a44be
