### ISSUE TITLE
Issues running locally

### ISSUE THREAD

**Issue by arnaudlimbourg** [ludovic-gonthier/snowshoe#23]
Hello,

I have tried running the project locally but the only thing I get are hundreds of API calls by which I mean the API call counter decreases very rapidly but nothing gets displayed on  screen :disappointed: There is nothing displayed in the console.

Is there anything I should look into?

**Comment by ludovic-gonthier** [comment]
Hi,

I have no erreur whith the last version of the master.
I tried to fetch my personnal PR and an organization team PR, both worked fine.

Which action did you do to have these hundreds of calls?

Have you run `gulp reactify`?

**Comment by arnaudlimbourg** [comment]
Weird, it loads fine, I authenticate to github, get back to the main screen and get just the navbar. When I click say on "Personal" I can see the counter decreasing like crazy and then stop.

**Comment by ludovic-gonthier** [comment]
Do you have loads of personnal opened PR ?

**Comment by arnaudlimbourg** [comment]
Not really no, less than 10 I would say.

Even  I let it run nothing gets displayed :(

**Comment by ludovic-gonthier** [comment]
Are those PR closed, or locked?

Those type of PR doesn't appear in the dashboard.
Then the API calls match the number of repository you have.

**Comment by arnaudlimbourg** [comment]
I have 8 open PR at the moment. The number of api calls far exceeds open+closed PR :)

Am I suppose to see my 8 open PR on the dashboard?

Where should I look to try and debug this?

**Comment by ludovic-gonthier** [comment]
What does the call to https://api.github.com/users/arnaudlimbourg/repos?access_token=your_access_token returns?

The access token is displayed on the terminal when you log in

Only the PR from repositories listed on the return of that call will be displayed on the 'Personnal' board.

**Comment by arnaudlimbourg** [comment]
A big JSON with all my repos data

**Comment by ludovic-gonthier** [comment]
Are the open PR on personnal repositories or on repositories your participated in?

**Comment by arnaudlimbourg** [comment]
I think I'm beginning to understand, none of my public repositories have opened PR, the PRs are opened on the original project. On private repositories I do have opened PRs but apparently private repos are not taken into account

**Comment by ludovic-gonthier** [comment]
I was thinking that too!
Maybe there's a missing board called 'Participating' listing all repositories from which you have participated?

**Comment by arnaudlimbourg** [comment]
That would be nice.

Is there a chance to have private repos in there?

**Comment by ludovic-gonthier** [comment]
Yes, maybe you could try to had a different parameter to the repository fetching function in `github-fetcher.js`. I was thinking of adding 'type=all' to the API call.

Here is the call done to fetch the personnal repo: https://developer.github.com/v3/repos/#list-user-repositories

**Comment by arnaudlimbourg** [comment]
I would think using https://developer.github.com/v3/repos/#list-your-repositories would be a more appropriate solution don't you think? As I understand it can also list your private repositories.

**Comment by ludovic-gonthier** [comment]
Yes, if this does what you expected to see, go for it!

**Comment by arnaudlimbourg** [comment]
Not pretty but changing to

``` javascript
repositories: function (url) {
       url = requester.GITHUB_BASE_URL + '/user/repos';
```

in github-fetcher works shows my private repos properly.

**Comment by ludovic-gonthier** [comment]
Ok,

Changing it here will break the teams PR functionnality. 
You can add a new button in the Navbar, juste like the 'Personnal' button (in views/components/navbar.jsx).

**Comment by ludovic-gonthier** [comment]
I remove the Bug label since it's not really one.

**Comment by arnaudlimbourg** [comment]
I may give it a spin at some point, closing this as it is not an issue (I'll propose a change to the Readme "Why don't I see anything?" :)
