### ISSUE TITLE
Unit/fonctional tests

### ISSUE THREAD

**Issue by fpietka** [ludovic-gonthier/snowshoe#28]
Would be nice to have some tests now.
Not sure about what test framework you should use (maybe ask @ludow).

I can give you a hand once you decide which framework you'd rather use :grin:

**Comment by ludovic-gonthier** [comment]
I totally agree with you!
We are using mocha on various project work, we can go for this framework!

**Comment by ludow** [comment]
For e2e tests, you could have a look to Nightwatch or maybe Protactor even if you're not using Angular.
