### ISSUE TITLE
Monitoring screen mode

### ISSUE THREAD

**Issue by fpietka** [ludovic-gonthier/snowshoe#29]
It would be nice to have an auto-logged/invite mode so monitoring screens don't have to be manually connected to SnowShoe interface.

**Comment by ludovic-gonthier** [comment]
I think that the API rate-limit of non-authenficated user won't be enought to display something relevant.
I already have an issue running to auto-log user in SnowShoe (see #7)

**Comment by fpietka** [comment]
I was thinking about using the Github access token there

**Comment by ludovic-gonthier** [comment]
Ok, I mis-understood the issue.

You're thinking of putting the access_token directly in the url, or using it in another way?

**Comment by fpietka** [comment]
Using an url parameter sounds good.

**Comment by bdronneau** [comment]
:+1:
