### ISSUE TITLE
Error in README for .env file ?

### ISSUE THREAD

**Issue by fpietka** [ludovic-gonthier/snowshoe#31]
In README for hostname you put the port in it. In fact when I did that in `.env` file, I got this strange output:

```
Informations:
        Hostname: ::
```

Removing the port in the hostname fixed it. Maybe that part should be changed?

**Comment by fpietka** [comment]
In fact there is two problem:
- SNOWSHOE_HOSTNAME should not have the port (in my case at least)
- `server.address()` returns `::` as address

**Comment by ludovic-gonthier** [comment]
We need a real SNOWSHOE_HOST variable to use in the OAuth part with Github.

I'll see what I can too at noon
