### ISSUE TITLE
UX : Dynamic size of thumbnail header

### ISSUE THREAD

**Issue by bdronneau** [ludovic-gonthier/snowshoe#32]
Hi,

I have a small problem with the UX when the repo name is too long. It's more a point of how it's displaying.

Currently, if the repo name is long we have this rendering : https://www.dropbox.com/s/hi14rejegur0avu/snowshoe_pr_not-align.png?dl=0

I think, a better way to display it's to adapt all height header PR ([thumbail header](https://github.com/ludovic-gonthier/snowshoe/blob/c8083e5910590e0b5d3e532d295c6ed50e30dbf4/views/components/github/pull-request.jsx#L27)) and have this rendering : https://www.dropbox.com/s/pl0c7g772blnjw8/snowshoe_pr_align.png?dl=0

What do you think about it ?

**Comment by ludovic-gonthier** [comment]
Hello,

Adapting the PR thumbnail height May look odd on other thumbnail with short length.
Still, we can handle the thumbnail length with a `text-overflow: ellipsis;` like the labels and adding a title to all PR thumbnails.

Whould that be relevant for you?

**Comment by bdronneau** [comment]
Too quick (: 

it's good for me
