### ISSUE TITLE
Feature request: sort PR by different values

### ISSUE THREAD

**Issue by j0k3r** [ludovic-gonthier/snowshoe#41]
It seems that PRs are sorted by the most recently updated at the bottom.
IMO this order isn't useful because if you have hundred of PR you'll have to scroll to the latest updated.

An option to define the date order (sort by most recently updated / least recently updated) could be great !

**Comment by ludovic-gonthier** [comment]
It is done at https://github.com/ludovic-gonthier/snowshoe/commit/5fe731130dc30101506d13d10c7361f8506776a7.

You can use any of the following key to sort:

```
updated_at
created_at
number
id
```

**Comment by j0k3r** [comment]
Thanks ! :rocket:
