### ISSUE TITLE
Avatars' getting black

### ISSUE THREAD

**Issue by fpietka** [ludovic-gonthier/snowshoe#42]
I'm currently using the version hosted at http://www.snowshoe.report/

After some time (may be after recovering from sleep mode, I'm not sure yet) some (not all) user's avatars are just filled with black, until I refresh the page.

**Comment by ludovic-gonthier** [comment]
This behaviour happens when a PullRequest is updated.
The avatar at its old place goes black. I tried to correct the glitch in [v1.1.2](https://github.com/ludovic-gonthier/snowshoe/tree/v1.1.2). But it seems that it did not entirely.

I'll investigate why it still have this behaviour

**Comment by ludovic-gonthier** [comment]
This should be fixed on the [v1.1.3](https://github.com/ludovic-gonthier/snowshoe/tree/v1.1.3).

**Comment by fpietka** [comment]
:+1:
