### ISSUE TITLE
Closing drop down menus

### ISSUE THREAD

**Issue by fpietka** [ludovic-gonthier/snowshoe#43]
The latest update of the navbar is great!

Although dropdown menus aren't closing, unless we click on them again. Would be nice if opening menu close the previous one, and also if clicking anywhere else closes menu as well.

**Comment by ludovic-gonthier** [comment]
Thanks for the feedback!
The dropdowns now correctly collapse on clicking out of it, or on opening another dropdown!

**Comment by fpietka** [comment]
:+1:
