### ISSUE TITLE
Handle reactions (feature request)

### ISSUE THREAD

**Issue by fpietka** [ludovic-gonthier/snowshoe#46]
It's still a preview feature in the API (hence the funky header), but it would be nice to have reaction in snowshoe: https://developer.github.com/v3/reactions/

**Comment by ludovic-gonthier** [comment]
It would be nice indeed, but I cannot see how to integrate them whithin the PR card.
Do you already have an idea of how it could be done?

**Comment by fpietka** [comment]
Not sure. I can see how I'd like to see it, but it might be too much related to our work flow. 
First of, I'm not sure displaying all emotions is a good idea as the card would have too much information on it. 
That being said, my use case would be seeing how much +1 and -1 to know how we stand on validation of the PR. So maybe just that? 

Let me know what you think about it.

**Comment by ludovic-gonthier** [comment]
Ok, if it is the concern of approving the PR, maybe we can wait to see if the PR approval will come into the API too: https://github.com/universe-2016 (The protect your merge part)

**Comment by fpietka** [comment]
I can't remember how long it took for reaction to get to the API, but you might be right.

**Comment by ludovic-gonthier** [comment]
I emailed them about the review state in the API and there is their response:

> Yeah, adding that to the API is on our wishlist, but I can't promise when it will happen. Please follow the blog for updates: https://developer.github.com/changes/

**Comment by ludovic-gonthier** [comment]
The feature is out since last December: https://developer.github.com/v3/pulls/reviews/.

I will work on the implementation of this feature on Snowshoe soon

**Comment by fpietka** [comment]
Nice, I wasn't aware of it.

**Comment by ludovic-gonthier** [comment]
The new release (https://github.com/ludovic-gonthier/snowshoe/releases/tag/1.3.0) fixes this issue.

The configuration of the CR required to validate a PR is in `config/front`
