### ISSUE TITLE
Can't scroll when there is too much teams

### ISSUE THREAD

**Issue by fpietka** [ludovic-gonthier/snowshoe#51]
When there is too much teams (or teams + organizations), we can't scroll down the list to reach some of them.

**Comment by ludovic-gonthier** [comment]
This issue has been taking care of and will ship with the next release.

I'll close the issue when it'll be on production

**Comment by fpietka** [comment]
Nice :+1:

**Comment by fpietka** [comment]
Nice :+1:Le 8 avr. 2017 16:47, Ludovic Gonthier <notifications@github.com> a écrit :This issue has been taking care of and will ship with the next release.
I'll close the issue when it'll be on production
