### ISSUE TITLE
Request authorisations too broad

### ISSUE THREAD

**Issue by fpietka** [ludovic-gonthier/snowshoe#53]
The main issue is about requested repository access (especially private):
* Code
* Issues
* Pull requests
* Wikis
* Settings
* Webhooks and services
* Deploy keys

The access to deploy keys can be concerning.

That being said, maybe it doesn't need wiki, settings nor webhooks.

About Personal user data, it may be enough to get read only, and maybe private data isn't required either.

Let me know what you think about it.

**Comment by ludovic-gonthier** [comment]
I do agree with you that the application doesn't need all those write permission but I can't see [scopes](https://developer.github.com/v3/oauth/#scopes) that fit better for what we need in Snowshoe.

Have you some scopes in mind that can be better than those actually in place?

**Comment by fpietka** [comment]
According to the documentation (https://developer.github.com/v3/oauth/#scopes), `repo_deployment` should be enough to get information about private repositories too (worth the try).

So maybe something like the following for the repo (basically everything except the main `repo` box):
* repo:status
 * repo_deployment
 * public_repo

and for the user:
* read:user

Security-wise, the goal would be to somehow avoid `deploy_keys` access, but I must say Github documentation isn't quite clear about that.

**Comment by ludovic-gonthier** [comment]
I'll try these today and see if they do the job and ship them with the soon to come next release

**Comment by fpietka** [comment]
Great!

**Comment by ludovic-gonthier** [comment]
A bit of information, 
If I omit the `repo` authorization, only the PR from public repositories are shown. And this is not quite what we want.

I can still put the `user` authorization to read-only though.
