### ISSUE TITLE
allow filters as GET params

### ISSUE THREAD

**Issue by senorihl** [ludovic-gonthier/snowshoe#58]
It would be great to "save" the filters in the URL as GET params in order to re-open a page marked as favorites (e.g. : labeled as **type/feat** and **status/mergeable** to `/:orgname/:repo/?label%5B%5D%3Dtype%2Ffeat%26label%5B%5D%3Dstatus%2Fmergeable`)

**Comment by ludovic-gonthier** [comment]
Hy @Senorihl, thank you for this issue.
I was originally thinking of storing those filters in the local storage. Will this solve your problem?

**Comment by senorihl** [comment]
Yep if I don't change the browser. I was thinking of GET params because it could allows users to share URL to another person or "forwarding" to mobile device etc.

**Comment by ludovic-gonthier** [comment]
Filters and orders are now part of the query. Let me see if you see some regression since last release
