### ISSUE TITLE
Instruction to use latest version?

### ISSUE THREAD

**Issue by j0k3r** [ludovic-gonthier/snowshoe#59]
We are still using the 1.2.6 version of want to upgrade to the latest.
However, I got an error when running `npm run build`:

```
ERROR in ./client/containers/DevTools.jsx
Module not found: Error: Cannot resolve module 'redux-devtools' in /home/ubuntu/snowshoe/client/containers
 @ ./client/containers/DevTools.jsx 11:21-46

ERROR in ./client/containers/DevTools.jsx
Module not found: Error: Cannot resolve module 'redux-devtools-log-monitor' in /home/ubuntu/snowshoe/client/containers
 @ ./client/containers/DevTools.jsx 13:31-68

ERROR in ./client/containers/DevTools.jsx
Module not found: Error: Cannot resolve module 'redux-devtools-dock-monitor' in /home/ubuntu/snowshoe/client/containers
 @ ./client/containers/DevTools.jsx 17:32-70
```

I've defined `NODE_ENV=production` in the `.env` file but I still got that error.
Also, I don't want to use the docker way to build it.

**Comment by ludovic-gonthier** [comment]
You seem to have installed node_modules without dev dependencies.
I've never done that and never saw this error before.

To go around this issue, you can just `npm i` instead of `npm i --production` to install devDependencies altogether.

**Comment by ludovic-gonthier** [comment]
version 1.4.0 has been released, you should'nt have any problem on `npm install --production` anymore.

Let me see if you see some regression since last release

**Comment by j0k3r** [comment]
Sorry for the very late reply, but it fixed the problem :+1:
